### PR TITLE
Script for Cashplan in Windows and running container

### PR DESCRIPTION
**Pull request by alaw005**
I have made these changes to work for my case, no hard feelings if you don't want to adopt. I think the RunCrashplanWindows10.vbs script could be particularly useful for people using Windows and having to select between local and remote instances of Crashplan.

### CODE REVIEW

**Comment by war59312** [comment]
Nice! Thanks.

FYI: Newer versions of CrashPlan also require:

\conf\ui_%UserName%.properties

Example: \conf\ui_William.properties

Within this file a new line gets added:

`serviceHost=%IPofRemoteHost%`

Example: serviceHost=192.168.10.135

You also need to stop CrashPlanService and restart it after making the files changes:

```
'Stop CrashPlanService
StopService ".", "CrashPlanService", True

'StartCrashPlanService
StartService ".", "CrashPlanService", True
```

And please add file ownership into the script itself using:

`cmd.exe /k takeown /f \"%1\" && icacls \"%1\" /grant Users:F`

Also need to close the CrashPlan system tray icon and reopen it so it displays correct info.

For now, I just use this batch file:

```
@ECHO OFF

COLOR FC

TITLE CrashPlan

GoTo GetAdminRights

:Author
REM "CREATED BY WAR59312"
REM "WAR59312@GMAIL.COM"
REM "21 AUG 2016"

:ChangeLog
REM "CREATED 21 AUG 2016"

:Requries
REM process.exe FROM http://retired.beyondlogic.org/solutions/processutil/processutil.htm
REM NoTrayOrphans.EXE FROM https://autohotkey.com/board/topic/80624-notrayorphans/
REM FOR process.exe AND NoTrayOrphans.exe, COPY TO WINDOWS SYSTEM32 AND SysWOW64 FOLIDERS SO THEY CAN BE RAN FROM ANYWHERE

REM MAKE SURE YOU SET PATHS BELOW
REM SEE LOCAL AND REMOTE PATHS - MAKE SURE YOU HAVE A COPY OF BOTH LOCAL AND REMOTE FILES IN THE SET LOCATIONS

:GetAdminRights
REM  --> Check For Permissions
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"

REM --> If Error Flag Set, We Do Not Have Admin Rights
if '%errorlevel%' NEQ '0' (
    echo Requesting Administrative Privileges...
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
REM Create UAC Prompt To Get Admin Rights
echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
echo args = "" >> "%temp%\getadmin.vbs"
echo For Each strArg in WScript.Arguments >> "%temp%\getadmin.vbs"
echo args = args ^& strArg ^& " "  >> "%temp%\getadmin.vbs"
echo Next >> "%temp%\getadmin.vbs"
echo UAC.ShellExecute "%~s0", args, "", "runas", 1 >> "%temp%\getadmin.vbs"

"%temp%\getadmin.vbs" %*
exit /B

:gotAdmin
if exist "%temp%\getadmin.vbs" ( del "%temp%\getadmin.vbs" )
pushd "%CD%"
CD /D "%~dp0"

:Paths
REM Set Paths Here
SET "CrashPlanPath=C:\ProgramData\CrashPlan"
SET "CrashPlanUiFileName=ui_William.properties"
SET "CrashPlanLOCAL=WILL"
SET "CrashPlanREMOTE=NAS"

:CheckIfPathsAreGood
REM Check If CrashPlanPath Is Set Correctly
IF NOT EXIST "%CrashPlanPath%\.ui_info" (
    ECHO CrashPlan Installed ^?
    ECHO.
    ECHO Bad Path Set ^?
    ECHO.
    ECHO "%CrashPlanPath%\.ui_info" Was NOT Found So Exiting
    ECHO.
    PAUSE
    GoTo End

REM ui_info Found So Do Nothing
)

REM Check If CrashPlanUiFileName Is Set Correctly
IF NOT EXIST "%CrashPlanPath%\conf\%CrashPlanUiFileName%" (
    ECHO Bad Path Set For CrashPlanUiFileName ^!
    ECHO.
    ECHO "%CrashPlanPath%\conf\%CrashPlanUiFileName%" Was NOT Found So Exiting
    ECHO.
    PAUSE
    GoTo End

REM CrashPlanUiFileName Found So Do Nothing
)

REM Check If CrashPlanLOCAL Is Set Correctly
IF NOT EXIST "%CrashPlanPath%\%CrashPlanLOCAL%\.ui_info" (
    ECHO Local Copy Of ui_info Created ^?
    ECHO.
    ECHO Bad Path Set ^?
    ECHO.
    ECHO "%CrashPlanPath%\%CrashPlanLOCAL%\.ui_info" Was NOT Found So Exiting
    ECHO.
    PAUSE
    GoTo End

REM ui_info Found So Do Nothing
)

REM Check If CrashPlanREMOTE Is Set Correctly
IF NOT EXIST "%CrashPlanPath%\%CrashPlanREMOTE%\.ui_info" (
    ECHO Remote Copy Of ui_info Created ^?
    ECHO.
    ECHO Bad Path Set ^?
    ECHO.
    ECHO "%CrashPlanPath%\%CrashPlanREMOTE%\.ui_info" Was NOT Found So Exiting
    ECHO.
    PAUSE
    GoTo End

REM ui_info Found So Do Nothing
)

REM Check If CrashPlanLOCAL Is Set Correctly
IF NOT EXIST "%CrashPlanPath%\conf\%CrashPlanLOCAL%\%CrashPlanUiFileName%" (
    ECHO Local Copy Of %CrashPlanUiFileName% Created ^?
    ECHO.
    ECHO Bad Path Set ^?
    ECHO.
    ECHO "%CrashPlanPath%\conf\%CrashPlanLOCAL%\%CrashPlanUiFileName%" Was NOT Found So Exiting
    ECHO.
    PAUSE
    GoTo End

REM ui_info Found So Do Nothing
)

REM Check If CrashPlanREMOTE Is Set Correctly
IF NOT EXIST "%CrashPlanPath%\conf\%CrashPlanREMOTE%\%CrashPlanUiFileName%" (
    ECHO Remote Copy Of %CrashPlanUiFileName% Created ^?
    ECHO.
    ECHO Bad Path Set ^?
    ECHO.
    ECHO "%CrashPlanPath%\conf\%CrashPlanREMOTE%\%CrashPlanUiFileName%" Was NOT Found So Exiting
    ECHO.
    PAUSE
    GoTo End

REM ui_info Found So Do Nothing
)

:FileRights
REM Make Sure Current User Has Rights To .ui_info And %CrashPlanUiFileName%
ECHO Y| icacls "%CrashPlanPath%\.ui_info" /C /grant %username%:(F) >NUL  2>NUL
ECHO Y| icacls "%CrashPlanPath%\conf\%CrashPlanUiFileName%" /C /grant %username%:(F) >NUL  2>NUL

:CheckIfRequriedFilesAreInstalled
REM Check If Requried Files Are Already Installed
IF NOT EXIST "%SystemRoot%\system32\process.exe" (

    REM Check If process.exe Exists In Current Folder
    IF EXIST "%cd%\process.exe" (
        REM Attempt To Automatically Install
        COPY "%cd%\process.exe" "%SystemRoot%\system32\" /Y >NUL  2>NUL
    ) ELSE (
        REM Failed To Automatically Install
        ECHO You Must First COPY process.exe To %SystemRoot%\system32\ Folder
        ECHO.
        ECHO Exiting
        ECHO.
        PAUSE
        GoTo End
    )
REM process Is Already Installed So Do Nothing
)

REM Check If Requried Files Are Already Installed
IF NOT EXIST "%SystemRoot%\SysWOW64\process.exe" (

    REM Check If process.exe Exists In Current Folder
    IF EXIST "%cd%\process.exe" (
        REM Attempt To Automatically Install
        COPY "%cd%\process.exe" "%SystemRoot%\SysWOW64\" /Y >NUL  2>NUL
    ) ELSE (
        REM Failed To Automatically Install
        ECHO You Must First COPY process.exe To %SystemRoot%\SysWOW64\ Folder
        ECHO.
        ECHO Exiting
        ECHO.
        PAUSE
        GoTo End
    )
REM process Is Already Installed So Do Nothing
)

REM Check If Requried Files Are Already Installed
IF NOT EXIST "%SystemRoot%\system32\NoTrayOrphans.exe" (

    REM Check If NoTrayOrphans.exe Exists In Current Folder
    IF EXIST "%cd%\NoTrayOrphans.exe" (
        REM Attempt To Automatically Install
        COPY "%cd%\NoTrayOrphans.exe" "%SystemRoot%\system32\" /Y >NUL  2>NUL
    ) ELSE (
        REM Failed To Automatically Install
        ECHO You Must First COPY NoTrayOrphans.exe To %SystemRoot%\system32\ Folder
        ECHO.
        ECHO Exiting
        ECHO.
        PAUSE
        GoTo End
    )
REM NoTrayOrphans Is Already Installed So Do Nothing
)

REM Check If Requried Files Are Already Installed
IF NOT EXIST "%SystemRoot%\SysWOW64\NoTrayOrphans.exe" (

    REM Check If NoTrayOrphans.exe Exists In Current Folder
    IF EXIST "%cd%\NoTrayOrphans.exe" (
        REM Attempt To Automatically Install
        COPY "%cd%\NoTrayOrphans.exe" "%SystemRoot%\SysWOW64\" /Y >NUL  2>NUL
    ) ELSE (
        REM Failed To Automatically Install
        ECHO You Must First COPY NoTrayOrphans.exe To %SystemRoot%\SysWOW64\ Folder
        ECHO.
        ECHO Exiting
        ECHO.
        PAUSE
        GoTo End
    )
REM NoTrayOrphans Is Already Installed So Do Nothing
)

:SwitchCrashPlanProfile
REM Switch CrashPlan Profile - local or NAS ? local Is The Default
SET CrashPlanProfile=local
SET /P CrashPlanProfile=local or nas ^?: (local) %=%
ECHO.

:CrashPlanProfile
REM Switch To Correct CrashPlan Profile
If /I "%CrashPlanProfile%"=="local" (
    GoTo LOCAL
)
If /I "%CrashPlanProfile%"=="nas" (
    GoTo NAS
) ELSE (
    ECHO Wrong^! local or nas Only^!
    ECHO.
    PAUSE
    EXIT
)

:LOCAL
REM ECHO Local
REM ECHO.

REM Stop CrashPlan Service
NET STOP crashplanservice >NUL  2>NUL
ECHO.

REM Make Damn Sure That CrashPlan System Tray Icon Is Killed
TASKKILL /F /IM CrashPlanTray.exe >nul 2>&1
PROCESS -q CrashPlanTray.exe >nul 2>&1
PROCESS -q CrashPlanTray.exe >nul 2>&1
TASKKILL /F /IM CrashPlanTray.exe >nul 2>&1

REM Make Sure CrashPlan System Tray Icon Is Gone
NoTrayOrphans

REM Make Sure .ui_info Is NOT Read Only
ATTRIB -r "%CrashPlanPath%\.ui_info" >NUL  2>NUL
ECHO.

REM COPY Over Local Version Of .ui_info
COPY /Y "%CrashPlanPath%\%CrashPlanLOCAL%\.ui_info" "%CrashPlanPath%\.ui_info" >NUL  2>NUL

REM Set .ui_info Back To Read Only
ATTRIB +r "%CrashPlanPath%\.ui_info" >NUL  2>NUL

ECHO.

REM Make Sure .properties File Is NOT Read Only
ATTRIB -r "%CrashPlanPath%\conf\%CrashPlanUiFileName%" >NUL  2>NUL
ECHO.

REM COPY Over Local Version Of .properties File
COPY /Y "%CrashPlanPath%\conf\%CrashPlanLOCAL%\%CrashPlanUiFileName%" "%CrashPlanPath%\conf\%CrashPlanUiFileName%" >NUL  2>NUL

REM Set .properties File Back To Read Only
ATTRIB +r "%CrashPlanPath%\conf\%CrashPlanUiFileName%" >NUL  2>NUL

ECHO.

REM START CrashPlan Service
NET START crashplanservice >NUL  2>NUL

REM Start CrashPlan Tray Icon
START /D"C:\Program Files\CrashPlan\" CrashPlanTray.exe

REM Start CrashPlan Desktop
START /D"C:\Program Files\CrashPlan\" CrashPlanDesktop.exe

GoTo END

:NAS
REM ECHO NAS
REM ECHO.

REM Stop CrashPlan Service
NET STOP crashplanservice >NUL  2>NUL
ECHO.

REM Make Damn Sure That CrashPlan System Tray Icon Is Killed
TASKKILL /F /IM CrashPlanTray.exe >nul 2>&1
PROCESS -q CrashPlanTray.exe >nul 2>&1
PROCESS -q CrashPlanTray.exe >nul 2>&1
TASKKILL /F /IM CrashPlanTray.exe >nul 2>&1

REM Make Sure CrashPlan System Tray Icon Is Gone
NoTrayOrphans

REM Make Sure .ui_info Is NOT Read Only
ATTRIB -r "%CrashPlanPath%\.ui_info" >NUL  2>NUL
ECHO.

REM COPY Over Remote NAS Version Of .ui_info
COPY /Y "%CrashPlanPath%\%CrashPlanREMOTE%\.ui_info" "%CrashPlanPath%\.ui_info" >NUL  2>NUL

REM Set .ui_info Back To Read Only
ATTRIB +r "%CrashPlanPath%\.ui_info" >NUL  2>NUL
ECHO.

REM Make Sure .properties File Is NOT Read Only
ATTRIB -r "%CrashPlanPath%\conf\%CrashPlanUiFileName%" >NUL  2>NUL
ECHO.

REM COPY Over Remote NAS Version Of .properties File
COPY /Y "%CrashPlanPath%\conf\%CrashPlanREMOTE%\%CrashPlanUiFileName%" "%CrashPlanPath%\conf\%CrashPlanUiFileName%" >NUL  2>NUL

REM Set .properties File Back To Read Only
ATTRIB +r "%CrashPlanPath%\conf\%CrashPlanUiFileName%" >NUL  2>NUL
ECHO.

REM START CrashPlan Service
NET START crashplanservice >NUL  2>NUL

REM Start CrashPlan Tray Icon
START /D"C:\Program Files\CrashPlan\" CrashPlanTray.exe

REM Start CrashPlan Desktop
START /D"C:\Program Files\CrashPlan\" CrashPlanDesktop.exe

GoTo END

:END
REM PAUSE
EXIT /b 0
```

**Comment by JrCs** [comment]
As i don't know vbs scripts, i cannot maintain your script.
Please open your own repository for the windows script.
Then i can add a link in the README about your repo for windows users.

**Comment by alaw005** [comment]
Fair enough. I have created this [repo](https://github.com/alaw005/docker-crashplan) with yours as a submodule.

**Comment by JrCs** [comment]
Good !

**Pull request closed without merging**
