### PR TITLE
add pro version to crashplan

### PR DESCRIPTION
**Pull request by MaraScott**

### CODE REVIEW

**Comment by visualinventor** [comment]
Any chance this can be merged in to get newly merged Crashplan business accounts up and running?

**Comment by edasque** [comment]
Do you really have to do anything? Mine just worked once I changed my account.

**Comment by visualinventor** [comment]
When I updated after the Crashplan pro switch I started seeing this on my Synology NAS.
https://github.com/JrCs/docker-crashplan/issues/35

**Comment by mszilagyi** [comment]
I am running into issues as well after upgrading to CrashPlan PRO with whats in master.  Pulled this patch down and built a new docker image based on it and am able to connect to the servers again.  I was about to go down the same path as visualinventor so glad I saw his PR first. Saved me some work :)

**Comment by vt2001cpe** [comment]
Can someone post directions how to incorporate the patch and build a new
docker image?

**Comment by MaraScott** [comment]
Hi Guys,

Feel free to test [my docker version](https://hub.docker.com/r/davask/d-crashplan/) or [my github version](https://github.com/davask/d-crashplan) on your own, I cannnot provide any garanty on data safety or anything else.

I can just tell you I use it since I switch to crashplan pro and so far so good.

below the Dockerfile I use:

```yaml
version: "3"

services:
  app:
    ports:
      - 4242:4242/tcp
      - 4243:4243/tcp
    environment:
      USR_ID: '<your user id>'
      USR_ID: '<your group id>'
      TZ: "<your timezone>"
    tty: true
    hostname: <your hostname>
    image: davask/d-crashplan:pro
    restart: always
    networks:
      - <your network>
    volumes:
      - /path/to/crashplan:/var/crashplan
      - /path/to/storage:/storage

networks:
    <your network>:
        external: true
```
anything between "<" and ">" (as <your network>) is to be replaced by your variables but I m guessing you already know that.

**Pull request closed without merging**
