### PR TITLE
Readme: Add hint on how to configure the local GUI

### PR DESCRIPTION
**Pull request by cfstras**
It took me some googling to find out how to do this, so I think it might be helpful to have here.

### CODE REVIEW

**Comment by noaho** [comment]
Don't you also have to change the host from 127.0.0.1 to your docker machine, and forward the port?

**Comment by cfstras** [comment]
Changed and rebased the patch. Better?

**Comment by JrCs** [comment]
Merged

**Comment by cfstras** [comment]
:thumbsup:

**Pull request closed without merging**
